server:
  port: 8046
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://192.168.1.185:3306/shop_user
    username: root
    password: customs
    driver-class-name: com.mysql.cj.jdbc.Driver

